// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'02551700a1195b8afbd028fb059b8717fe35ce1124fec269ebdc5988a140f1ac'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Classes: {
      readonly class: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['output'];
    };
    readonly CommandHashes: {
      readonly command_name: CodecTypes['pg/text@1']['output'];
      readonly file_hash: CodecTypes['pg/text@1']['output'];
    };
    readonly DiscordEventWarnings: {
      readonly message_id: CodecTypes['pg/text@1']['output'];
      readonly channel_id: CodecTypes['pg/text@1']['output'];
      readonly event_id: CodecTypes['pg/text@1']['output'];
    };
    readonly FeatureFlags: {
      readonly guild_id: CodecTypes['pg/text@1']['output'];
      readonly flags: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly Guilds: {
      readonly guild_name: CodecTypes['pg/text@1']['output'];
      readonly guild_id: CodecTypes['pg/text@1']['output'];
      readonly clusters: CodecTypes['pg/text@1']['output'] | null;
    };
    readonly Interactions: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly message_id: CodecTypes['pg/text@1']['output'];
      readonly guild_name: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'] | null;
      readonly role_name: CodecTypes['pg/text@1']['output'] | null;
      readonly user_name: CodecTypes['pg/text@1']['output'];
      readonly channel_name: CodecTypes['pg/text@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly thread_name: CodecTypes['pg/text@1']['output'] | null;
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    };
    readonly OnlineMembers: {
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
    };
    readonly Polls: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly poll_hash: CodecTypes['pg/text@1']['output'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['output'];
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly poll_question: CodecTypes['pg/text@1']['output'];
      readonly response1_text: CodecTypes['pg/text@1']['output'];
      readonly response1_value: CodecTypes['pg/int4@1']['output'];
      readonly response2_text: CodecTypes['pg/text@1']['output'];
      readonly response2_value: CodecTypes['pg/int4@1']['output'];
      readonly response3_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response3_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response4_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response4_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response5_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response5_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response6_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response6_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response7_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response7_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response8_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response8_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response9_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response9_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response10_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response10_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
    };
    readonly ZoomMeetings: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly department: CodecTypes['pg/text@1']['output'] | null;
      readonly duration_in_minutes: CodecTypes['pg/int4@1']['output'];
      readonly host_email: CodecTypes['pg/text@1']['output'];
      readonly metting_creation_source: CodecTypes['pg/text@1']['output'];
      readonly metting_group: CodecTypes['pg/text@1']['output'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly started_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly ended_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly meeting_id: CodecTypes['pg/text@1']['output'];
      readonly max_simultaneous_views: CodecTypes['pg/int4@1']['output'];
      readonly host_name: CodecTypes['pg/text@1']['output'] | null;
      readonly max_entries: CodecTypes['pg/int4@1']['output'];
      readonly meeting_type: CodecTypes['pg/text@1']['output'];
      readonly max_unique_views: CodecTypes['pg/int4@1']['output'];
      readonly place: CodecTypes['pg/text@1']['output'] | null;
      readonly total_participants_minutes: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Classes: {
      readonly class: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['input'];
    };
    readonly CommandHashes: {
      readonly command_name: CodecTypes['pg/text@1']['input'];
      readonly file_hash: CodecTypes['pg/text@1']['input'];
    };
    readonly DiscordEventWarnings: {
      readonly message_id: CodecTypes['pg/text@1']['input'];
      readonly channel_id: CodecTypes['pg/text@1']['input'];
      readonly event_id: CodecTypes['pg/text@1']['input'];
    };
    readonly FeatureFlags: {
      readonly guild_id: CodecTypes['pg/text@1']['input'];
      readonly flags: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly Guilds: {
      readonly guild_name: CodecTypes['pg/text@1']['input'];
      readonly guild_id: CodecTypes['pg/text@1']['input'];
      readonly clusters: CodecTypes['pg/text@1']['input'] | null;
    };
    readonly Interactions: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly message_id: CodecTypes['pg/text@1']['input'];
      readonly guild_name: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'] | null;
      readonly role_name: CodecTypes['pg/text@1']['input'] | null;
      readonly user_name: CodecTypes['pg/text@1']['input'];
      readonly channel_name: CodecTypes['pg/text@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly thread_name: CodecTypes['pg/text@1']['input'] | null;
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
    };
    readonly OnlineMembers: {
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
    };
    readonly Polls: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly poll_hash: CodecTypes['pg/text@1']['input'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['input'];
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly poll_question: CodecTypes['pg/text@1']['input'];
      readonly response1_text: CodecTypes['pg/text@1']['input'];
      readonly response1_value: CodecTypes['pg/int4@1']['input'];
      readonly response2_text: CodecTypes['pg/text@1']['input'];
      readonly response2_value: CodecTypes['pg/int4@1']['input'];
      readonly response3_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response3_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response4_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response4_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response5_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response5_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response6_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response6_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response7_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response7_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response8_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response8_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response9_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response9_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response10_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response10_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
    };
    readonly ZoomMeetings: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly department: CodecTypes['pg/text@1']['input'] | null;
      readonly duration_in_minutes: CodecTypes['pg/int4@1']['input'];
      readonly host_email: CodecTypes['pg/text@1']['input'];
      readonly metting_creation_source: CodecTypes['pg/text@1']['input'];
      readonly metting_group: CodecTypes['pg/text@1']['input'] | null;
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly started_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly ended_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly meeting_id: CodecTypes['pg/text@1']['input'];
      readonly max_simultaneous_views: CodecTypes['pg/int4@1']['input'];
      readonly host_name: CodecTypes['pg/text@1']['input'] | null;
      readonly max_entries: CodecTypes['pg/int4@1']['input'];
      readonly meeting_type: CodecTypes['pg/text@1']['input'];
      readonly max_unique_views: CodecTypes['pg/int4@1']['input'];
      readonly place: CodecTypes['pg/text@1']['input'] | null;
      readonly total_participants_minutes: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly classes: {
      readonly class: CodecTypes['pg/text@1']['output'];
      readonly guild_name: CodecTypes['pg/text@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly command_hashes: {
      readonly command_name: CodecTypes['pg/text@1']['output'];
      readonly file_hash: CodecTypes['pg/text@1']['output'];
    };
    readonly discord_event_warnings: {
      readonly channel_id: CodecTypes['pg/text@1']['output'];
      readonly event_id: CodecTypes['pg/text@1']['output'];
      readonly message_id: CodecTypes['pg/text@1']['output'];
    };
    readonly featureFlags: {
      readonly flags: CodecTypes['pg/jsonb@1']['output'] | null;
      readonly guild_id: CodecTypes['pg/text@1']['output'];
    };
    readonly guilds: {
      readonly clusters: CodecTypes['pg/text@1']['output'] | null;
      readonly guild_id: CodecTypes['pg/text@1']['output'];
      readonly guild_name: CodecTypes['pg/text@1']['output'];
    };
    readonly interactions: {
      readonly category: CodecTypes['pg/text@1']['output'] | null;
      readonly channel_name: CodecTypes['pg/text@1']['output'];
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly message: CodecTypes['pg/text@1']['output'];
      readonly message_id: CodecTypes['pg/text@1']['output'];
      readonly role_name: CodecTypes['pg/text@1']['output'] | null;
      readonly thread_name: CodecTypes['pg/text@1']['output'] | null;
      readonly user_name: CodecTypes['pg/text@1']['output'];
    };
    readonly online_members: {
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly quantity: CodecTypes['pg/int4@1']['output'];
    };
    readonly polls: {
      readonly category: CodecTypes['pg/text@1']['output'];
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['output'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly poll_hash: CodecTypes['pg/text@1']['output'] | null;
      readonly poll_question: CodecTypes['pg/text@1']['output'];
      readonly response1_text: CodecTypes['pg/text@1']['output'];
      readonly response1_value: CodecTypes['pg/int4@1']['output'];
      readonly response10_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response10_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response2_text: CodecTypes['pg/text@1']['output'];
      readonly response2_value: CodecTypes['pg/int4@1']['output'];
      readonly response3_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response3_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response4_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response4_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response5_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response5_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response6_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response6_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response7_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response7_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response8_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response8_value: CodecTypes['pg/int4@1']['output'] | null;
      readonly response9_text: CodecTypes['pg/text@1']['output'] | null;
      readonly response9_value: CodecTypes['pg/int4@1']['output'] | null;
    };
    readonly zoom_meetings: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly department: CodecTypes['pg/text@1']['output'] | null;
      readonly duration_in_minutes: CodecTypes['pg/int4@1']['output'];
      readonly ended_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly host_email: CodecTypes['pg/text@1']['output'];
      readonly host_name: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly max_entries: CodecTypes['pg/int4@1']['output'];
      readonly max_simultaneous_views: CodecTypes['pg/int4@1']['output'];
      readonly max_unique_views: CodecTypes['pg/int4@1']['output'];
      readonly meeting_id: CodecTypes['pg/text@1']['output'];
      readonly meeting_type: CodecTypes['pg/text@1']['output'];
      readonly metting_creation_source: CodecTypes['pg/text@1']['output'];
      readonly metting_group: CodecTypes['pg/text@1']['output'] | null;
      readonly place: CodecTypes['pg/text@1']['output'] | null;
      readonly started_at: CodecTypes['pg/timestamp-temporal@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly total_participants_minutes: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly classes: {
      readonly class: CodecTypes['pg/text@1']['input'];
      readonly guild_name: CodecTypes['pg/text@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly command_hashes: {
      readonly command_name: CodecTypes['pg/text@1']['input'];
      readonly file_hash: CodecTypes['pg/text@1']['input'];
    };
    readonly discord_event_warnings: {
      readonly channel_id: CodecTypes['pg/text@1']['input'];
      readonly event_id: CodecTypes['pg/text@1']['input'];
      readonly message_id: CodecTypes['pg/text@1']['input'];
    };
    readonly featureFlags: {
      readonly flags: CodecTypes['pg/jsonb@1']['input'] | null;
      readonly guild_id: CodecTypes['pg/text@1']['input'];
    };
    readonly guilds: {
      readonly clusters: CodecTypes['pg/text@1']['input'] | null;
      readonly guild_id: CodecTypes['pg/text@1']['input'];
      readonly guild_name: CodecTypes['pg/text@1']['input'];
    };
    readonly interactions: {
      readonly category: CodecTypes['pg/text@1']['input'] | null;
      readonly channel_name: CodecTypes['pg/text@1']['input'];
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly message: CodecTypes['pg/text@1']['input'];
      readonly message_id: CodecTypes['pg/text@1']['input'];
      readonly role_name: CodecTypes['pg/text@1']['input'] | null;
      readonly thread_name: CodecTypes['pg/text@1']['input'] | null;
      readonly user_name: CodecTypes['pg/text@1']['input'];
    };
    readonly online_members: {
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly quantity: CodecTypes['pg/int4@1']['input'];
    };
    readonly polls: {
      readonly category: CodecTypes['pg/text@1']['input'];
      readonly dt: CodecTypes['pg/timestamp-temporal@1']['input'] | null;
      readonly guild_name: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly poll_hash: CodecTypes['pg/text@1']['input'] | null;
      readonly poll_question: CodecTypes['pg/text@1']['input'];
      readonly response1_text: CodecTypes['pg/text@1']['input'];
      readonly response1_value: CodecTypes['pg/int4@1']['input'];
      readonly response10_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response10_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response2_text: CodecTypes['pg/text@1']['input'];
      readonly response2_value: CodecTypes['pg/int4@1']['input'];
      readonly response3_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response3_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response4_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response4_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response5_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response5_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response6_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response6_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response7_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response7_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response8_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response8_value: CodecTypes['pg/int4@1']['input'] | null;
      readonly response9_text: CodecTypes['pg/text@1']['input'] | null;
      readonly response9_value: CodecTypes['pg/int4@1']['input'] | null;
    };
    readonly zoom_meetings: {
      readonly created_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly department: CodecTypes['pg/text@1']['input'] | null;
      readonly duration_in_minutes: CodecTypes['pg/int4@1']['input'];
      readonly ended_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly host_email: CodecTypes['pg/text@1']['input'];
      readonly host_name: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly max_entries: CodecTypes['pg/int4@1']['input'];
      readonly max_simultaneous_views: CodecTypes['pg/int4@1']['input'];
      readonly max_unique_views: CodecTypes['pg/int4@1']['input'];
      readonly meeting_id: CodecTypes['pg/text@1']['input'];
      readonly meeting_type: CodecTypes['pg/text@1']['input'];
      readonly metting_creation_source: CodecTypes['pg/text@1']['input'];
      readonly metting_group: CodecTypes['pg/text@1']['input'] | null;
      readonly place: CodecTypes['pg/text@1']['input'] | null;
      readonly started_at: CodecTypes['pg/timestamp-temporal@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly total_participants_minutes: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly classes: {
              columns: {
                readonly class: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly guild_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              uniques: readonly [{ readonly columns: readonly ['class']; readonly name: 'class' }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly command_hashes: {
              columns: {
                readonly command_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly file_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['command_name'];
                readonly name: 'command_hashes_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly discord_event_warnings: {
              columns: {
                readonly message_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly channel_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly event_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['message_id'];
                readonly name: 'discord_event_warnings_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly featureFlags: {
              columns: {
                readonly guild_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly flags: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['guild_id'];
                readonly name: 'featureFlags_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly guilds: {
              columns: {
                readonly guild_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly guild_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly clusters: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
              };
              primaryKey: {
                readonly columns: readonly ['guild_name'];
                readonly name: 'guilds_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly interactions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly message_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly guild_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly role_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly user_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly channel_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly message: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly thread_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly dt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'interactions_pkey' };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'idx_message_id';
                  readonly columns: readonly ['message_id'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly online_members: {
              columns: {
                readonly dt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
                readonly quantity: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['dt'];
                readonly name: 'online_members_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly polls: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly poll_hash: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly guild_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly category: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly poll_question: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly response1_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly response1_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly response2_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly response2_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly response3_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response3_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response4_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response4_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response5_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response5_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response6_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response6_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response7_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response7_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response8_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response8_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response9_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response9_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly response10_text: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly response10_value: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly dt: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: true;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              primaryKey: { readonly columns: readonly ['id']; readonly name: 'polls_pkey' };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly zoom_meetings: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly department: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly duration_in_minutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly host_email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly metting_creation_source: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly metting_group: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
                readonly started_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
                readonly ended_at: {
                  readonly nativeType: 'timestamp';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly nullable: false;
                  readonly typeParams: { readonly precision: 0 };
                };
                readonly meeting_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly max_simultaneous_views: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly host_name: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly max_entries: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly meeting_type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly max_unique_views: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly place: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly total_participants_minutes: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: {
                readonly columns: readonly ['id'];
                readonly name: 'zoom_meetings_pkey';
              };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly classes: { readonly namespace: 'public' & NamespaceId; readonly model: 'Classes' };
    readonly command_hashes: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'CommandHashes';
    };
    readonly discord_event_warnings: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DiscordEventWarnings';
    };
    readonly featureFlags: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'FeatureFlags';
    };
    readonly guilds: { readonly namespace: 'public' & NamespaceId; readonly model: 'Guilds' };
    readonly interactions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'Interactions';
    };
    readonly online_members: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'OnlineMembers';
    };
    readonly polls: { readonly namespace: 'public' & NamespaceId; readonly model: 'Polls' };
    readonly zoom_meetings: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ZoomMeetings';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Classes: {
            readonly fields: {
              readonly class: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly quantity: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly guild_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'classes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly class: { readonly column: 'class' };
                readonly quantity: { readonly column: 'quantity' };
                readonly guild_name: { readonly column: 'guild_name' };
              };
            };
          };
          readonly CommandHashes: {
            readonly fields: {
              readonly command_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly file_hash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'command_hashes';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly command_name: { readonly column: 'command_name' };
                readonly file_hash: { readonly column: 'file_hash' };
              };
            };
          };
          readonly DiscordEventWarnings: {
            readonly fields: {
              readonly message_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly channel_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly event_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'discord_event_warnings';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly message_id: { readonly column: 'message_id' };
                readonly channel_id: { readonly column: 'channel_id' };
                readonly event_id: { readonly column: 'event_id' };
              };
            };
          };
          readonly FeatureFlags: {
            readonly fields: {
              readonly guild_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly flags: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'featureFlags';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly guild_id: { readonly column: 'guild_id' };
                readonly flags: { readonly column: 'flags' };
              };
            };
          };
          readonly Guilds: {
            readonly fields: {
              readonly guild_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly guild_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly clusters: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'guilds';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly guild_name: { readonly column: 'guild_name' };
                readonly guild_id: { readonly column: 'guild_id' };
                readonly clusters: { readonly column: 'clusters' };
              };
            };
          };
          readonly Interactions: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly message_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly guild_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly category: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly role_name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly user_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly channel_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly message: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly thread_name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly dt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'interactions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly message_id: { readonly column: 'message_id' };
                readonly guild_name: { readonly column: 'guild_name' };
                readonly category: { readonly column: 'category' };
                readonly role_name: { readonly column: 'role_name' };
                readonly user_name: { readonly column: 'user_name' };
                readonly channel_name: { readonly column: 'channel_name' };
                readonly message: { readonly column: 'message' };
                readonly thread_name: { readonly column: 'thread_name' };
                readonly dt: { readonly column: 'dt' };
              };
            };
          };
          readonly OnlineMembers: {
            readonly fields: {
              readonly dt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              readonly quantity: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'online_members';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly dt: { readonly column: 'dt' };
                readonly quantity: { readonly column: 'quantity' };
              };
            };
          };
          readonly Polls: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly poll_hash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly guild_name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly poll_question: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response1_text: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response1_value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response2_text: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response2_value: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response3_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response3_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response4_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response4_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response5_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response5_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response6_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response6_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response7_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response7_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response8_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response8_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response9_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response9_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly response10_text: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly response10_value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly dt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'polls';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly poll_hash: { readonly column: 'poll_hash' };
                readonly guild_name: { readonly column: 'guild_name' };
                readonly category: { readonly column: 'category' };
                readonly poll_question: { readonly column: 'poll_question' };
                readonly response1_text: { readonly column: 'response1_text' };
                readonly response1_value: { readonly column: 'response1_value' };
                readonly response2_text: { readonly column: 'response2_text' };
                readonly response2_value: { readonly column: 'response2_value' };
                readonly response3_text: { readonly column: 'response3_text' };
                readonly response3_value: { readonly column: 'response3_value' };
                readonly response4_text: { readonly column: 'response4_text' };
                readonly response4_value: { readonly column: 'response4_value' };
                readonly response5_text: { readonly column: 'response5_text' };
                readonly response5_value: { readonly column: 'response5_value' };
                readonly response6_text: { readonly column: 'response6_text' };
                readonly response6_value: { readonly column: 'response6_value' };
                readonly response7_text: { readonly column: 'response7_text' };
                readonly response7_value: { readonly column: 'response7_value' };
                readonly response8_text: { readonly column: 'response8_text' };
                readonly response8_value: { readonly column: 'response8_value' };
                readonly response9_text: { readonly column: 'response9_text' };
                readonly response9_value: { readonly column: 'response9_value' };
                readonly response10_text: { readonly column: 'response10_text' };
                readonly response10_value: { readonly column: 'response10_value' };
                readonly dt: { readonly column: 'dt' };
              };
            };
          };
          readonly ZoomMeetings: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly department: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly duration_in_minutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly host_email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metting_creation_source: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metting_group: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly created_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              readonly started_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              readonly ended_at: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamp-temporal@1';
                  readonly typeParams: { readonly precision: 0 };
                };
              };
              readonly meeting_id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly max_simultaneous_views: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly host_name: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly max_entries: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly meeting_type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly max_unique_views: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly place: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly total_participants_minutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'zoom_meetings';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly title: { readonly column: 'title' };
                readonly department: { readonly column: 'department' };
                readonly duration_in_minutes: { readonly column: 'duration_in_minutes' };
                readonly host_email: { readonly column: 'host_email' };
                readonly metting_creation_source: { readonly column: 'metting_creation_source' };
                readonly metting_group: { readonly column: 'metting_group' };
                readonly created_at: { readonly column: 'created_at' };
                readonly started_at: { readonly column: 'started_at' };
                readonly ended_at: { readonly column: 'ended_at' };
                readonly meeting_id: { readonly column: 'meeting_id' };
                readonly max_simultaneous_views: { readonly column: 'max_simultaneous_views' };
                readonly host_name: { readonly column: 'host_name' };
                readonly max_entries: { readonly column: 'max_entries' };
                readonly meeting_type: { readonly column: 'meeting_type' };
                readonly max_unique_views: { readonly column: 'max_unique_views' };
                readonly place: { readonly column: 'place' };
                readonly total_participants_minutes: {
                  readonly column: 'total_participants_minutes';
                };
              };
            };
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
